// Generated by CoffeeScript 1.6.1
(function() {

  window.FlightFactory = (function() {
    var FlightListParser, instance;

    function FlightFactory() {}

    instance = null;

    FlightListParser = (function() {
      var flightList;

      flightList = new Array();

      function FlightListParser(url) {
        this.url = url;
        this.createFlightList();
      }

      FlightListParser.prototype.createFlightList = function() {
        return jQuery.ajax({
          url: this.url,
          dataType: 'jsonp',
          jsonp: 'jsonp',
          jsonpCallback: 'jsonCallback',
          error: function(a, b, e) {
            alert(e);
            return console.log(e);
          },
          success: function(data) {
            var f, tmpFlight, _i, _len, _ref;
            _ref = data['flights']['flight'];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              f = _ref[_i];
              tmpFlight = new Flight(f);
              flightList.push(tmpFlight);
            }
            return onFlightLoadComplete(flightList);
          }
        });
      };

      FlightListParser.prototype.getFlight = function(flightId) {
        var i, tmpLst, _i, _ref;
        tmpLst = new Array();
        for (i = _i = 0, _ref = flightList.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
          if (flightList[i].flightId.toUpperCase() === flightId.toUpperCase()) {
            tmpLst.push(flightList[i]);
          }
        }
        return tmpLst;
      };

      return FlightListParser;

    })();

    FlightFactory.getInstance = function(url) {
      return instance != null ? instance : instance = new FlightListParser(url);
    };

    return FlightFactory;

  })();

  /*
  val = new UrlBuilder('http://flydata.avinor.no/XmlFeed.asp?', "OSL").timeFrom(2).timeTo(4).direction("a").buildUrl()
  console.log(val)
  */


}).call(this);
