// Generated by CoffeeScript 1.6.1
(function() {
  var Flight;

  window.FlightManager = (function() {

    function FlightManager() {}

    FlightManager._FLIGHTS_ARRAY;

    FlightManager._AIRPORT_MAP = [];

    FlightManager._AVINOR_AIRPORT_URL = new UrlBuilder('http://freberg.org/xmlproxy.php?url=', 'http://flydata.avinor.no/airportNames.asp?', '').build();

    FlightManager._AVINOR_FLIGHT_URL = new UrlBuilder('http://freberg.org/xmlproxy.php?url=', 'http://flydata.avinor.no/XmlFeed.asp?', 'OSL').timeFrom(0).timeTo(24).direction('D').build();

    FlightManager.prototype.fetchFlights = function(successCallback, errorCallback) {
      if (!window.navigator.onLine) {
        if (errorCallback != null) {
          errorCallback('Er ikke koblet til internett. Kan ikke hente fly.');
        }
        if (successCallback != null) {
          FlightManager._FLIGHTS_ARRAY = new Array();
          return successCallback(Flights._FLIGHTS_ARRAY);
        }
      }
      return jQuery.ajax({
        url: FlightManager._AVINOR_FLIGHT_URL,
        dataType: 'jsonp',
        jsonp: 'jsonp',
        jsonpCallback: 'jsonCallback',
        error: function(a, b, e) {
          if (errorCallback != null) {
            return errorCallback(e);
          }
        },
        success: function(data) {
          var f, tmpFlight, _i, _len, _ref, _results;
          FlightManager._FLIGHTS_ARRAY = new Array();
          _ref = data['flights']['flight'];
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            f = _ref[_i];
            tmpFlight = new Flight(f);
            _results.push(FlightManager._FLIGHTS_ARRAY.push(tmpFlight));
          }
          return _results;
        },
        complete: function() {
          FlightManager._FLIGHTS_ARRAY.sort(function(aa, bb) {
            if (aa.flightId < bb.flightId) {
              return -1;
            } else if (aa.flightId > bb.flightId) {
              return 1;
            } else {
              return 0;
            }
          });
          return successCallback(FlightManager._FLIGHTS_ARRAY);
        }
      });
    };

    FlightManager.prototype.getFlightsById = function(id, count) {
      var e, num, tmpLst, _i, _len, _ref;
      if (FlightManager._FLIGHTS_ARRAY != null) {
        tmpLst = new Array();
        id = id.toUpperCase();
        num = 0;
        _ref = FlightManager._FLIGHTS_ARRAY;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          e = _ref[_i];
          if (id === e.flightId.substring(0, id.length)) {
            tmpLst.push(e);
            num++;
          }
          if (num >= count) {
            break;
          }
        }
      } else {
        throw new Error("Har ikke hentet ned flyinformasjon");
      }
      return tmpLst;
    };

    FlightManager.prototype.getAirportNameById = function(id, callback, errorCallback) {
      var flight;
      id = id.toUpperCase().trim();
      try {
        flight = FlightManager._AIRPORT_MAP[id];
        if (flight == null) {
          return this.fetchAirportNameById(id, callback, errorCallback);
        } else {
          return callback(flight);
        }
      } catch (error) {
        FlightManager._AIRPORT_MAP[id] = id;
        errorCallback('Feil ved henting av flyplass, bruker flyplass kode');
        return callback(id);
      }
    };

    FlightManager.prototype.fetchAirportNameById = function(id, completeCallback, errorCallback) {
      var dataHolder, url;
      if (!window.navigator.onLine) {
        if (errorCallback != null) {
          errorCallback('Er ikke koblet til internett, bruker flyplass koder');
        }
        if (completeCallback != null) {
          return completeCallback(id);
        }
      }
      dataHolder = "";
      url = FlightManager._AVINOR_AIRPORT_URL += id;
      return jQuery.ajax({
        url: url,
        dataType: 'jsonp',
        jsonp: 'jsonp',
        jsonpCallback: 'jsonCallback',
        error: function(a, b, e) {
          return console.log(e);
        },
        success: function(data) {
          return dataHolder = data;
        },
        complete: function() {
          var airportName, tmp;
          airportName = id;
          try {
            tmp = dataHolder['airportName']['@attributes']['name'];
            FlightManager._AVINOR_AIRPORT_URL[id] = tmp;
            airportName = tmp;
          } catch (e) {
            if (errorCallback != null) {
              errorCallback('Feil ved henting av flyplass, bruker flyplass kode');
            }
          }
          if ((airportName != null) && (completeCallback != null)) {
            return completeCallback(airportName);
          }
        }
      });
    };

    return FlightManager;

  })();

  Flight = (function() {

    function Flight(flightObject) {
      var day, hours, minutes, month, tmpDate;
      this.uniqueId = flightObject['@attributes']['uniqueID'];
      this.flightId = flightObject['flight_id'].toUpperCase();
      this.dom_int = flightObject['dom_int'];
      tmpDate = new Date(flightObject['schedule_time']);
      minutes = tmpDate.getMinutes();
      hours = tmpDate.getHours();
      day = tmpDate.getDay();
      month = tmpDate.getMonth();
      if (minutes < 10) {
        minutes = "0" + minutes;
      }
      if (hours < 10) {
        hours = "0" + hours;
      }
      if (day < 10) {
        day = "0" + day;
      }
      if (month < 10) {
        month = "0" + month;
      }
      this.schedule_time = "Kl: " + hours + ":" + minutes + " - " + day + "/" + month;
      this.arr_dep = flightObject['arr_dep'];
      this.airport = flightObject['airport'];
      this.via_airport(flightObject);
      this.check_in(flightObject);
      this.gate(flightObject);
      this.status(flightObject);
    }

    Flight.prototype.via_airport = function(val) {
      if (val['airport'] != null) {
        this.via_airport = val['airport'];
      } else {
        this.via_airport = "";
      }
      return this;
    };

    Flight.prototype.check_in = function(val) {
      if (val['check_in'] != null) {
        this.check_in = val['check_in'];
      } else {
        this.check_in = "";
      }
      return this;
    };

    Flight.prototype.gate = function(val) {
      if (val['gate'] != null) {
        this.gate = val['gate'];
      } else {
        this.gate = "";
      }
      return this;
    };

    Flight.prototype.status = function(val) {
      var code, time;
      if (val['status'] != null) {
        code = val.status['@attributes'].code;
        time = val.status['@attributes'].time;
        if (code == null) {
          code = "";
        }
        if (time == null) {
          time = "";
        }
        this.status_code = code;
        this.status_time = time;
      } else {
        this.status_code = "";
        this.status_time = "";
      }
      return this;
    };

    return Flight;

  })();

}).call(this);
