// Generated by CoffeeScript 1.6.2
(function() {
  window.FlightUrlBuilder = (function() {
    function FlightUrlBuilder(proxy, url, airport) {
      this.proxy = proxy;
      this.url = url;
      this.url += "airport=" + airport.toUpperCase() + "&";
    }

    FlightUrlBuilder.prototype.timeFrom = function(timeFrom) {
      this.url += "timeFrom=" + timeFrom + "&";
      return this;
    };

    FlightUrlBuilder.prototype.timeTo = function(timeTo) {
      this.url += "timeTo=" + timeTo + "&";
      return this;
    };

    FlightUrlBuilder.prototype.direction = function(direction) {
      direction = direction.toUpperCase();
      if (direction === 'A' || direction === 'D') {
        this.url += "direction=" + direction + "&";
        return this;
      } else {
        throw new Error("Illegal direction (A or D is required, you entered " + direction + ")");
      }
    };

    FlightUrlBuilder.prototype.lastUpdate = function(lastUpdate) {
      this.url += "lastUpdate=" + lastUpdate + "&";
      return this;
    };

    FlightUrlBuilder.prototype.build = function() {
      this.url = encodeURIComponent(this.url.substring(0, this.url.lastIndexOf("&")));
      return this.proxy + this.url;
    };

    return FlightUrlBuilder;

  })();

}).call(this);
