// Generated by CoffeeScript 1.6.2
(function() {
  window.GeoLocationManager = (function() {
    var _instance, _location;

    function GeoLocationManager() {}

    _instance = new GeoLocationManager();

    _location = null;

    GeoLocationManager.prototype.fetchLocation = function(useHighAccuracy) {
      if (useHighAccuracy == null) {
        useHighAccuracy = false;
      }
      return navigator.geolocation.getCurrentPosition(this.onPositionSuccess, this.onPositionError, {
        maximumAge: 10 * 60 * 1000,
        timeout: 5000,
        enableHighAccuracy: useHighAccuracy
      });
    };

    GeoLocationManager.prototype.getCurrentLocation = function() {
      return _location;
    };

    GeoLocationManager.prototype.onPositionSuccess = function(param) {
      return _location = param;
    };

    GeoLocationManager.prototype.onPositionError = function(error) {
      return console.log(error);
    };

    GeoLocationManager.getInstance = function() {
      return _instance;
    };

    return GeoLocationManager;

  })();

}).call(this);
