// Generated by CoffeeScript 1.6.1

/*
flightUrl = new UrlBuilder('http://freberg.org/xmlproxy.php?url=', 'http://flydata.avinor.no/XmlFeed.asp?', 'OSL').timeFrom(0).timeTo(1).direction('D').build()

errorFunc = (msg) ->
  console.log("Init.errorFunc " + msg)

func = (airportname) ->
  console.log("Init.func " + airportname)

Flight.fetchFlights(flightUrl, (data) ->
  console.log("Init.Flight.fetchFlights ")
  console.dir(data)

  Flight.getAirportNameById('OSL', func, errorFunc)
  #Flight.getAirportNameById('OSL', func, errorFunc)
  #Flight.getAirportNameById('CPH', func)
  #Flight.getAirportNameById('AAH', func)
  #Flight.getAirportNameById('AAH', func)
  #Flight.getAirportNameById('ACH', func)
)
*/


(function() {



}).call(this);
