// Generated by CoffeeScript 1.6.2
(function() {
  window.LoadScreen = (function() {
    var instance, notificationLabelId;

    function LoadScreen() {}

    notificationLabelId = '#loadingText';

    instance = new LoadScreen();

    LoadScreen.prototype.start = function() {
      var flightManager;

      if (window.navigator.onLine) {
        GeoLocationManager.getInstance().fetchLocation(true);
        TrainStationManager.getInstance().fetchAllTrainStations();
        flightManager = FlightManager.getInstance();
        return flightManager.fetchFlights(instance.onLoadComplete, instance.onLoadFail);
      } else {
        return $(notificationLabelId).val('Du må være koblet til internett for å bruke denne applikasjonen');
      }
    };

    LoadScreen.prototype.onLoadComplete = function(arr) {
      console.dir(arr);
      $.mobile.changePage("#transportationSelectionScreen", "fade");
      return TransportationSelectionScreen.getInstance().reset();
    };

    LoadScreen.prototype.onLoadFail = function(err) {
      return $(notificationLabelId).val('Feil ved henting av flydata');
    };

    LoadScreen.getInstance = function() {
      return instance;
    };

    return LoadScreen;

  })();

}).call(this);
