// Generated by CoffeeScript 1.6.1
(function() {

  window.StartPage = (function() {
    var fetchFlightsCallback, reportError;

    StartPage._FLIGHT_URL = new UrlBuilder('http://freberg.org/xmlproxy.php?url=', 'http://flydata.avinor.no/XmlFeed.asp?', 'OSL').timeFrom(0).timeTo(24).direction('D').build();

    StartPage._FLIGHTS;

    reportError = function(error) {
      return console.log(error);
    };

    fetchFlightsCallback = function(flights) {
      StartPage._FLIGHTS = flights;
      return console.dir(flights);
    };

    function StartPage(flightsList, flightsLabelNotifaction) {
      this.flightsList = flightsList;
      this.flightsLabelNotifaction = flightsLabelNotifaction;
      Flight.fetchFlights(StartPage._FLIGHT_URL, fetchFlightsCallback, reportError);
    }

    StartPage.prototype.onFlightSearchChange = function(newValue) {
      var count, e, newFlights, _i, _len;
      if ((newValue != null) && (this.flightsList != null) && (StartPage._FLIGHTS != null) && (this.flightsLabelNotifaction != null)) {
        this.flightsList.empty();
        this.flightsLabelNotifaction.text('');
        if (newValue.length > 0) {
          count = 5;
          newFlights = Flight.getFlightsById(newValue, count);
          console.dir(newFlights);
          if (newFlights.length === count) {
            this.flightsLabelNotifaction.text('Rafiner søket for flere resultater: ');
          } else if (newFlights.length === 0) {
            this.flightsLabelNotifaction.text('Fant ingen flyavganger med søkeord: ' + newValue);
          }
          for (_i = 0, _len = newFlights.length; _i < _len; _i++) {
            e = newFlights[_i];
            if (e != null) {
              this.flightsList.append('<li><table class="flightSearchResultElement"><tr><td>' + e.flightId + '</td><td>' + e.schedule_time + '</td><td>' + e.airport + '</td></tr></table></li>');
            }
          }
          return $(this.flightsList).listview("refresh");
        }
      }
    };

    return StartPage;

  })();

}).call(this);
