// Generated by CoffeeScript 1.6.2
(function() {
  window.ThePosition = (function() {
    var resultD;

    resultD = null;

    ThePosition.prototype.geolocationError = function(error) {
      return console.log(error);
    };

    ThePosition.prototype.geolocationSuccess = function(pos) {
      if ((resultD != null) && (pos != null)) {
        return resultD.html("Lat:" + pos.coords.latitude + "<br />" + "Lon:" + pos.coords.longitude + "<br />" + "Acc:" + pos.coords.accuracy + "<br />");
      }
    };

    function ThePosition(resultDiv) {
      resultD = resultDiv;
    }

    ThePosition.prototype.getPosition = function() {
      return navigator.geolocation.getCurrentPosition(this.geolocationSuccess, this.geolocationError);
    };

    return ThePosition;

  })();

}).call(this);
