// Generated by CoffeeScript 1.6.1
(function() {

  window.UrlBuilder = (function() {

    function UrlBuilder(proxy, url, airport) {
      this.proxy = proxy;
      this.url = url;
      this.url += "airport=" + airport.toUpperCase() + "&";
    }

    UrlBuilder.prototype.timeFrom = function(timeFrom) {
      this.url += "timeFrom=" + timeFrom + "&";
      return this;
    };

    UrlBuilder.prototype.timeTo = function(timeTo) {
      this.url += "timeTo=" + timeTo + "&";
      return this;
    };

    UrlBuilder.prototype.direction = function(direction) {
      direction = direction.toUpperCase();
      if (direction === 'A' || direction === 'D') {
        this.url += "direction=" + direction + "&";
        return this;
      } else {
        throw new Error("Illegal direction (A or D is required, you entered " + direction + ")");
      }
    };

    UrlBuilder.prototype.lastUpdate = function(lastUpdate) {
      this.url += "lastUpdate=" + lastUpdate + "&";
      return this;
    };

    UrlBuilder.prototype.build = function() {
      this.url = encodeURIComponent(this.url.substring(0, this.url.lastIndexOf("&")));
      return this.proxy + this.url;
    };

    return UrlBuilder;

  })();

}).call(this);
